### ISSUE TITLE
Support Gradle Kotlin DSL

### ISSUE THREAD

**Issue by fletchgqc** [kontrolilo/kontrolilo#72]
I tried this on my project with a build.gradle.kts file and it said:

`Check the licenses of the gradle environment..................(no files to check)Skipped`

Since Kotlin is quite popular, it would be nice if this were supported.

**Comment by fletchgqc** [comment]
Since https://github.com/renovatebot/renovate handles dependencies in various formats including the Kotlin DSL, maybe you should allow their code to inspire you.

**Comment by nbyl** [comment]
If I read the documentation correctly, simply adding build.gradle.kts to the filelist should make this work.

**Comment by fletchgqc** [comment]
@nbyl,could you please link to the part of the documentation you are referring to? I couldn't find it.

**Comment by fletchgqc** [comment]
Ping

**Comment by nbyl** [comment]
@fletchgqc Using a current version of pre-commit and kontrolilo should be able to check the kotlin version.
